services:
  postgres-datasource:
    image: postgres:17.8
    container_name: postgres-datasource
    environment:
      POSTGRES_USER: ${BANKCORESYSTEM_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${BANKCORESYSTEM_DATASOURCE_PASSWORD}
      DATASOURCE_DB_NAME_ACCOUNTS: ${DATASOURCE_DB_NAME_ACCOUNTS}
      DATASOURCE_DB_NAME_CUSTOMERS: ${DATASOURCE_DB_NAME_CUSTOMERS}
    ports:
      - "5432:5432"
    volumes:
      - ./bankcore-system-data:/var/lib/postgresql/data
      - ./init-multiple-db.sh:/docker-entrypoint-initdb.d/init-multiple-db.sh
    restart: always

  ms-customers:
    build:
      context: ./ms-customers
    container_name: ms-customers
    ports:
      - "8081:8081"
    depends_on:
      - postgres-datasource
    environment:
      SPRING_DATASOURCE_URL_CUSTOMERS: jdbc:postgresql://postgres-datasource:5432/${DATASOURCE_DB_NAME_CUSTOMERS}
      BANKCORESYSTEM_DATASOURCE_USERNAME: ${BANKCORESYSTEM_DATASOURCE_USERNAME}
      BANKCORESYSTEM_DATASOURCE_PASSWORD: ${BANKCORESYSTEM_DATASOURCE_PASSWORD}
      BANKCORESYSTEM_SECRET_KEY: ${BANKCORESYSTEM_SECRET_KEY}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_MAX_AGE: ${CORS_MAX_AGE}
      SWAGGER_UI_DOCUMENTATION_ENABLED: ${SWAGGER_UI_DOCUMENTATION_ENABLED}
    restart: on-failure

  ms-accounts:
    build:
      context: ./ms-accounts
    container_name: ms-accounts
    ports:
      - "8082:8082"
    depends_on:
      - postgres-datasource
      - ms-customers
    environment:
      SPRING_DATASOURCE_URL_ACCOUNTS: jdbc:postgresql://postgres-datasource:5432/${DATASOURCE_DB_NAME_ACCOUNTS}
      BANKCORESYSTEM_DATASOURCE_USERNAME: ${BANKCORESYSTEM_DATASOURCE_USERNAME}
      BANKCORESYSTEM_DATASOURCE_PASSWORD: ${BANKCORESYSTEM_DATASOURCE_PASSWORD}
      BANKCORESYSTEM_SECRET_KEY: ${BANKCORESYSTEM_SECRET_KEY}
      CUSTOMERS_SERVICE_URL: http://ms-customers:8081
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_MAX_AGE: ${CORS_MAX_AGE}
      BANKCORESYSTEM_LIMIT_CHECKING: ${BANKCORESYSTEM_LIMIT_CHECKING}
      BANKCORESYSTEM_LIMIT_SAVINGS: ${BANKCORESYSTEM_LIMIT_SAVINGS}
    restart: on-failure
