#!/bin/bash
set -e

echo "starting databases: $DATASOURCE_DB_NAME_ACCOUNTS, $DATASOURCE_DB_NAME_CUSTOMERS, $DATASOURCE_DB_NAME_ACCOUNTS_TEST y $DATASOURCE_DB_NAME_CUSTOMERS_TEST"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE "$DATASOURCE_DB_NAME_ACCOUNTS";
  CREATE DATABASE "$DATASOURCE_DB_NAME_CUSTOMERS";
  CREATE DATABASE "$DATASOURCE_DB_NAME_ACCOUNTS_TEST";
  CREATE DATABASE "$DATASOURCE_DB_NAME_CUSTOMERS_TEST";
EOSQL