#!/bin/bash
set -e

echo "starting databases: $DATASOURCE_DB_NAME_ACCOUNTS y $DATASOURCE_DB_NAME_CUSTOMERS"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE "$DATASOURCE_DB_NAME_ACCOUNTS";
  CREATE DATABASE "$DATASOURCE_DB_NAME_CUSTOMERS";
EOSQL