spring.application.name=ms-accounts

server.port=${SERVER_PORT:8082}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.datasource.url=${SPRING_DATASOURCE_URL_ACCOUNTS}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.oauth2.resourceserver.jwt.secret-key=${SPRING_SECRET_KEY:Vg7oLpj6hBVR110xqJS2YolB74fezRptMEw1+Pb4/xk=}
