# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5433/${BANKCORESYTEM_DATASOURCE_DB_NAME_CUSTOMERS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${BANKCORESYTEM_DATASOURCE_USERNAME}
spring.datasource.password=${BANKCORESYTEM_DATASOURCE_PASSWORD}

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Swagger UI
swagger-ui.documentation.enabled=false