spring.application.name=ms-customers

server.port=8081
spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.url=${SPRING_DATASOURCE_URL_CUSTOMERS:jdbc:postgresql://localhost:5433/customers_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:username-customers}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password-customers}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de Documentacion
springdoc.api-docs.enabled=${SWAGGER_UI_DOCUMENTATION_ENABLED:true}
springdoc.swagger-ui.enabled=${SWAGGER_UI_DOCUMENTATION_ENABLED:true}
springdoc.api-docs.version=OPENAPI_3_0